#!/usr/bin/env python

#Inspired by https://raw.githubusercontent.com/stevekrenzel/autoreload/
import os
import signal
import sys
import subprocess
import time
from checksumdir import dirhash

def file_filter(name):
    return (not name.startswith(".")) and (not name.endswith(".swp"))

def print_stdout(process):
    stdout = process.stdout
    if stdout != None:
        print(stdout)


# We concatenate all of the arguments together, and treat that as the command to run
command = ' '.join(sys.argv[1:])

# The path to watch
path = os.getcwd()

# How often we check the filesystem for changes (in seconds)
wait = 1

# The process to autoreload
process = subprocess.Popen(command)

#The current directory checksum
last_dirhash = dirhash(path, 'md5')

print("Watching {}".format(path))
while True:
    this_dirhash = dirhash(path, 'md5')
    if this_dirhash != last_dirhash:
        print('Restarting process.')

        os.kill(process.pid,signal.SIGINT)
        process = subprocess.Popen(command)

        last_dirhash = this_dirhash

    time.sleep(wait)
