# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/funnel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/funnel.proto',
  package='buda.entities',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x62uda/entities/funnel.proto\x12\rbuda.entities\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n\x0b\x46unnelEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tfunnel_id\x18\x04 \x01(\t\x12\x17\n\x0f\x66unnel_event_id\x18\x05 \x01(\t\x12&\n\x04tags\x18\x06 \x03(\x0b\x32\x18.buda.entities.FunnelTag\"\'\n\tFunnelTag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FUNNELEVENT = _descriptor.Descriptor(
  name='FunnelEvent',
  full_name='buda.entities.FunnelEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.entities.FunnelEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.entities.FunnelEvent.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.entities.FunnelEvent.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funnel_id', full_name='buda.entities.FunnelEvent.funnel_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funnel_event_id', full_name='buda.entities.FunnelEvent.funnel_event_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='buda.entities.FunnelEvent.tags', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=253,
)


_FUNNELTAG = _descriptor.Descriptor(
  name='FunnelTag',
  full_name='buda.entities.FunnelTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='buda.entities.FunnelTag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='buda.entities.FunnelTag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=294,
)

_FUNNELEVENT.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FUNNELEVENT.fields_by_name['tags'].message_type = _FUNNELTAG
DESCRIPTOR.message_types_by_name['FunnelEvent'] = _FUNNELEVENT
DESCRIPTOR.message_types_by_name['FunnelTag'] = _FUNNELTAG

FunnelEvent = _reflection.GeneratedProtocolMessageType('FunnelEvent', (_message.Message,), dict(
  DESCRIPTOR = _FUNNELEVENT,
  __module__ = 'buda.entities.funnel_pb2'
  # @@protoc_insertion_point(class_scope:buda.entities.FunnelEvent)
  ))
_sym_db.RegisterMessage(FunnelEvent)

FunnelTag = _reflection.GeneratedProtocolMessageType('FunnelTag', (_message.Message,), dict(
  DESCRIPTOR = _FUNNELTAG,
  __module__ = 'buda.entities.funnel_pb2'
  # @@protoc_insertion_point(class_scope:buda.entities.FunnelTag)
  ))
_sym_db.RegisterMessage(FunnelTag)


# @@protoc_insertion_point(module_scope)
