# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/utm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/utm.proto',
  package='buda.entities',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x62uda/entities/utm.proto\x12\rbuda.entities\"V\n\x03Utm\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06medium\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61mpaign\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0c\n\x04term\x18\x05 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UTM = _descriptor.Descriptor(
  name='Utm',
  full_name='buda.entities.Utm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='buda.entities.Utm.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='medium', full_name='buda.entities.Utm.medium', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='campaign', full_name='buda.entities.Utm.campaign', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='buda.entities.Utm.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term', full_name='buda.entities.Utm.term', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Utm'] = _UTM

Utm = _reflection.GeneratedProtocolMessageType('Utm', (_message.Message,), dict(
  DESCRIPTOR = _UTM,
  __module__ = 'buda.entities.utm_pb2'
  # @@protoc_insertion_point(class_scope:buda.entities.Utm)
  ))
_sym_db.RegisterMessage(Utm)


# @@protoc_insertion_point(module_scope)
