# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from buda.entities import funnel_event_pb2 as buda_dot_entities_dot_funnel__event__pb2
from buda.entities import funnel_pb2 as buda_dot_entities_dot_funnel__pb2
from buda.services import events_collector_pb2 as buda_dot_services_dot_events__collector__pb2


class EventsCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TrackFunnel = channel.unary_unary(
        '/buda.services.EventsCollector/TrackFunnel',
        request_serializer=buda_dot_entities_dot_funnel__pb2.Funnel.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__pb2.Response.FromString,
        )
    self.TrackFunnelEvent = channel.unary_unary(
        '/buda.services.EventsCollector/TrackFunnelEvent',
        request_serializer=buda_dot_entities_dot_funnel__event__pb2.FunnelEvent.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__pb2.Response.FromString,
        )


class EventsCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TrackFunnel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TrackFunnelEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventsCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TrackFunnel': grpc.unary_unary_rpc_method_handler(
          servicer.TrackFunnel,
          request_deserializer=buda_dot_entities_dot_funnel__pb2.Funnel.FromString,
          response_serializer=buda_dot_services_dot_events__collector__pb2.Response.SerializeToString,
      ),
      'TrackFunnelEvent': grpc.unary_unary_rpc_method_handler(
          servicer.TrackFunnelEvent,
          request_deserializer=buda_dot_entities_dot_funnel__event__pb2.FunnelEvent.FromString,
          response_serializer=buda_dot_services_dot_events__collector__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'buda.services.EventsCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
