# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from buda.entities import action_taken_pb2 as buda_dot_entities_dot_action__taken__pb2
from buda.entities import funnel_event_pb2 as buda_dot_entities_dot_funnel__event__pb2
from buda.entities import funnel_pb2 as buda_dot_entities_dot_funnel__pb2
from buda.entities import signin_pb2 as buda_dot_entities_dot_signin__pb2
from buda.entities import signup_pb2 as buda_dot_entities_dot_signup__pb2
from buda.entities import subscription_cancelled_pb2 as buda_dot_entities_dot_subscription__cancelled__pb2
from buda.entities import subscription_created_pb2 as buda_dot_entities_dot_subscription__created__pb2
from buda.entities import subscription_period_updated_pb2 as buda_dot_entities_dot_subscription__period__updated__pb2
from buda.entities import visit_pb2 as buda_dot_entities_dot_visit__pb2
from buda.services import events_collector_service_pb2 as buda_dot_services_dot_events__collector__service__pb2


class EventsCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectFunnel = channel.unary_unary(
        '/buda.EventsCollector/CollectFunnel',
        request_serializer=buda_dot_entities_dot_funnel__pb2.Funnel.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectFunnelEvent = channel.unary_unary(
        '/buda.EventsCollector/CollectFunnelEvent',
        request_serializer=buda_dot_entities_dot_funnel__event__pb2.FunnelEvent.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectVisit = channel.unary_unary(
        '/buda.EventsCollector/CollectVisit',
        request_serializer=buda_dot_entities_dot_visit__pb2.Visit.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectSignup = channel.unary_unary(
        '/buda.EventsCollector/CollectSignup',
        request_serializer=buda_dot_entities_dot_signup__pb2.Signup.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectSignin = channel.unary_unary(
        '/buda.EventsCollector/CollectSignin',
        request_serializer=buda_dot_entities_dot_signin__pb2.Signin.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectActionTaken = channel.unary_unary(
        '/buda.EventsCollector/CollectActionTaken',
        request_serializer=buda_dot_entities_dot_action__taken__pb2.ActionTaken.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectSubscriptionCreated = channel.unary_unary(
        '/buda.EventsCollector/CollectSubscriptionCreated',
        request_serializer=buda_dot_entities_dot_subscription__created__pb2.SubscriptionCreated.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectSubscriptionPeriodUpdated = channel.unary_unary(
        '/buda.EventsCollector/CollectSubscriptionPeriodUpdated',
        request_serializer=buda_dot_entities_dot_subscription__period__updated__pb2.SubscriptionPeriodUpdated.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )
    self.CollectSubscriptionCancelled = channel.unary_unary(
        '/buda.EventsCollector/CollectSubscriptionCancelled',
        request_serializer=buda_dot_entities_dot_subscription__cancelled__pb2.SubscriptionCancelled.SerializeToString,
        response_deserializer=buda_dot_services_dot_events__collector__service__pb2.Response.FromString,
        )


class EventsCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CollectFunnel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectFunnelEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectVisit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectSignup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectSignin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectActionTaken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectSubscriptionCreated(self, request, context):
    """Subscription Events
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectSubscriptionPeriodUpdated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectSubscriptionCancelled(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventsCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectFunnel': grpc.unary_unary_rpc_method_handler(
          servicer.CollectFunnel,
          request_deserializer=buda_dot_entities_dot_funnel__pb2.Funnel.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectFunnelEvent': grpc.unary_unary_rpc_method_handler(
          servicer.CollectFunnelEvent,
          request_deserializer=buda_dot_entities_dot_funnel__event__pb2.FunnelEvent.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectVisit': grpc.unary_unary_rpc_method_handler(
          servicer.CollectVisit,
          request_deserializer=buda_dot_entities_dot_visit__pb2.Visit.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectSignup': grpc.unary_unary_rpc_method_handler(
          servicer.CollectSignup,
          request_deserializer=buda_dot_entities_dot_signup__pb2.Signup.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectSignin': grpc.unary_unary_rpc_method_handler(
          servicer.CollectSignin,
          request_deserializer=buda_dot_entities_dot_signin__pb2.Signin.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectActionTaken': grpc.unary_unary_rpc_method_handler(
          servicer.CollectActionTaken,
          request_deserializer=buda_dot_entities_dot_action__taken__pb2.ActionTaken.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectSubscriptionCreated': grpc.unary_unary_rpc_method_handler(
          servicer.CollectSubscriptionCreated,
          request_deserializer=buda_dot_entities_dot_subscription__created__pb2.SubscriptionCreated.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectSubscriptionPeriodUpdated': grpc.unary_unary_rpc_method_handler(
          servicer.CollectSubscriptionPeriodUpdated,
          request_deserializer=buda_dot_entities_dot_subscription__period__updated__pb2.SubscriptionPeriodUpdated.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
      'CollectSubscriptionCancelled': grpc.unary_unary_rpc_method_handler(
          servicer.CollectSubscriptionCancelled,
          request_deserializer=buda_dot_entities_dot_subscription__cancelled__pb2.SubscriptionCancelled.FromString,
          response_serializer=buda_dot_services_dot_events__collector__service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'buda.EventsCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
