# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/services/events_collector_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import funnel_pb2 as buda_dot_entities_dot_funnel__pb2
from buda.entities import funnel_event_pb2 as buda_dot_entities_dot_funnel__event__pb2
from buda.entities import visit_pb2 as buda_dot_entities_dot_visit__pb2
from buda.entities import signup_pb2 as buda_dot_entities_dot_signup__pb2
from buda.entities import signin_pb2 as buda_dot_entities_dot_signin__pb2
from buda.entities import action_taken_pb2 as buda_dot_entities_dot_action__taken__pb2
from buda.entities import subscription_created_pb2 as buda_dot_entities_dot_subscription__created__pb2
from buda.entities import subscription_cancelled_pb2 as buda_dot_entities_dot_subscription__cancelled__pb2
from buda.entities import subscription_period_updated_pb2 as buda_dot_entities_dot_subscription__period__updated__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/services/events_collector_service.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,buda/services/events_collector_service.proto\x12\x04\x62uda\x1a\x1a\x62uda/entities/funnel.proto\x1a buda/entities/funnel_event.proto\x1a\x19\x62uda/entities/visit.proto\x1a\x1a\x62uda/entities/signup.proto\x1a\x1a\x62uda/entities/signin.proto\x1a buda/entities/action_taken.proto\x1a(buda/entities/subscription_created.proto\x1a*buda/entities/subscription_cancelled.proto\x1a/buda/entities/subscription_period_updated.proto\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xba\x04\n\x0f\x45ventsCollector\x12/\n\rCollectFunnel\x12\x0c.buda.Funnel\x1a\x0e.buda.Response\"\x00\x12\x39\n\x12\x43ollectFunnelEvent\x12\x11.buda.FunnelEvent\x1a\x0e.buda.Response\"\x00\x12-\n\x0c\x43ollectVisit\x12\x0b.buda.Visit\x1a\x0e.buda.Response\"\x00\x12/\n\rCollectSignup\x12\x0c.buda.Signup\x1a\x0e.buda.Response\"\x00\x12/\n\rCollectSignin\x12\x0c.buda.Signin\x1a\x0e.buda.Response\"\x00\x12\x39\n\x12\x43ollectActionTaken\x12\x11.buda.ActionTaken\x1a\x0e.buda.Response\"\x00\x12I\n\x1a\x43ollectSubscriptionCreated\x12\x19.buda.SubscriptionCreated\x1a\x0e.buda.Response\"\x00\x12U\n CollectSubscriptionPeriodUpdated\x12\x1f.buda.SubscriptionPeriodUpdated\x1a\x0e.buda.Response\"\x00\x12M\n\x1c\x43ollectSubscriptionCancelled\x12\x1b.buda.SubscriptionCancelled\x1a\x0e.buda.Response\"\x00\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_funnel__pb2.DESCRIPTOR,buda_dot_entities_dot_funnel__event__pb2.DESCRIPTOR,buda_dot_entities_dot_visit__pb2.DESCRIPTOR,buda_dot_entities_dot_signup__pb2.DESCRIPTOR,buda_dot_entities_dot_signin__pb2.DESCRIPTOR,buda_dot_entities_dot_action__taken__pb2.DESCRIPTOR,buda_dot_entities_dot_subscription__created__pb2.DESCRIPTOR,buda_dot_entities_dot_subscription__cancelled__pb2.DESCRIPTOR,buda_dot_entities_dot_subscription__period__updated__pb2.DESCRIPTOR,])




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='buda.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='buda.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=395,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'buda.services.events_collector_service_pb2'
  # @@protoc_insertion_point(class_scope:buda.Response)
  ))
_sym_db.RegisterMessage(Response)



_EVENTSCOLLECTOR = _descriptor.ServiceDescriptor(
  name='EventsCollector',
  full_name='buda.EventsCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=398,
  serialized_end=968,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectFunnel',
    full_name='buda.EventsCollector.CollectFunnel',
    index=0,
    containing_service=None,
    input_type=buda_dot_entities_dot_funnel__pb2._FUNNEL,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectFunnelEvent',
    full_name='buda.EventsCollector.CollectFunnelEvent',
    index=1,
    containing_service=None,
    input_type=buda_dot_entities_dot_funnel__event__pb2._FUNNELEVENT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectVisit',
    full_name='buda.EventsCollector.CollectVisit',
    index=2,
    containing_service=None,
    input_type=buda_dot_entities_dot_visit__pb2._VISIT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSignup',
    full_name='buda.EventsCollector.CollectSignup',
    index=3,
    containing_service=None,
    input_type=buda_dot_entities_dot_signup__pb2._SIGNUP,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSignin',
    full_name='buda.EventsCollector.CollectSignin',
    index=4,
    containing_service=None,
    input_type=buda_dot_entities_dot_signin__pb2._SIGNIN,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectActionTaken',
    full_name='buda.EventsCollector.CollectActionTaken',
    index=5,
    containing_service=None,
    input_type=buda_dot_entities_dot_action__taken__pb2._ACTIONTAKEN,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSubscriptionCreated',
    full_name='buda.EventsCollector.CollectSubscriptionCreated',
    index=6,
    containing_service=None,
    input_type=buda_dot_entities_dot_subscription__created__pb2._SUBSCRIPTIONCREATED,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSubscriptionPeriodUpdated',
    full_name='buda.EventsCollector.CollectSubscriptionPeriodUpdated',
    index=7,
    containing_service=None,
    input_type=buda_dot_entities_dot_subscription__period__updated__pb2._SUBSCRIPTIONPERIODUPDATED,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectSubscriptionCancelled',
    full_name='buda.EventsCollector.CollectSubscriptionCancelled',
    index=8,
    containing_service=None,
    input_type=buda_dot_entities_dot_subscription__cancelled__pb2._SUBSCRIPTIONCANCELLED,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSCOLLECTOR)

DESCRIPTOR.services_by_name['EventsCollector'] = _EVENTSCOLLECTOR

# @@protoc_insertion_point(module_scope)
