# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/funnel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/funnel.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x62uda/entities/funnel.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n\x06\x46unnel\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x04 \x01(\t\x12$\n\x04tags\x18\x05 \x03(\x0b\x32\x16.buda.Funnel.TagsEntry\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FUNNEL_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='buda.Funnel.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='buda.Funnel.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='buda.Funnel.TagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=302,
)

_FUNNEL = _descriptor.Descriptor(
  name='Funnel',
  full_name='buda.Funnel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Funnel.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.Funnel.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.Funnel.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='buda.Funnel.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='buda.Funnel.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FUNNEL_TAGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=302,
)

_FUNNEL_TAGSENTRY.containing_type = _FUNNEL
_FUNNEL.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNEL.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNEL.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FUNNEL.fields_by_name['tags'].message_type = _FUNNEL_TAGSENTRY
DESCRIPTOR.message_types_by_name['Funnel'] = _FUNNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Funnel = _reflection.GeneratedProtocolMessageType('Funnel', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _FUNNEL_TAGSENTRY,
    __module__ = 'buda.entities.funnel_pb2'
    # @@protoc_insertion_point(class_scope:buda.Funnel.TagsEntry)
    ))
  ,
  DESCRIPTOR = _FUNNEL,
  __module__ = 'buda.entities.funnel_pb2'
  # @@protoc_insertion_point(class_scope:buda.Funnel)
  ))
_sym_db.RegisterMessage(Funnel)
_sym_db.RegisterMessage(Funnel.TagsEntry)


_FUNNEL_TAGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
