# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/payment_schedule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/payment_schedule.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$buda/entities/payment_schedule.proto\x12\x04\x62uda*K\n\x0fPaymentSchedule\x12\x0b\n\x07MONTHLY\x10\x00\x12\r\n\tQUARTERLY\x10\x01\x12\x0e\n\nBIANNUALLY\x10\x02\x12\x0c\n\x08\x41NNUALLY\x10\x03\x62\x06proto3')
)

_PAYMENTSCHEDULE = _descriptor.EnumDescriptor(
  name='PaymentSchedule',
  full_name='buda.PaymentSchedule',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MONTHLY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUARTERLY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIANNUALLY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNUALLY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=46,
  serialized_end=121,
)
_sym_db.RegisterEnumDescriptor(_PAYMENTSCHEDULE)

PaymentSchedule = enum_type_wrapper.EnumTypeWrapper(_PAYMENTSCHEDULE)
MONTHLY = 0
QUARTERLY = 1
BIANNUALLY = 2
ANNUALLY = 3


DESCRIPTOR.enum_types_by_name['PaymentSchedule'] = _PAYMENTSCHEDULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
