# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/payment_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/payment_type.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n buda/entities/payment_type.proto\x12\x04\x62uda*R\n\x0bPaymentType\x12\n\n\x06STRIPE\x10\x00\x12\t\n\x05\x41PPLE\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\x12\t\n\x05\x43HECK\x10\x03\x12\x08\n\x04\x42\x41NK\x10\x04\x12\n\n\x06PAYPAL\x10\x05\x62\x06proto3')
)

_PAYMENTTYPE = _descriptor.EnumDescriptor(
  name='PaymentType',
  full_name='buda.PaymentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRIPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BANK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYPAL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=42,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_PAYMENTTYPE)

PaymentType = enum_type_wrapper.EnumTypeWrapper(_PAYMENTTYPE)
STRIPE = 0
APPLE = 1
ANDROID = 2
CHECK = 3
BANK = 4
PAYPAL = 5


DESCRIPTOR.enum_types_by_name['PaymentType'] = _PAYMENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
