# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/signup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buda.entities import product_pb2 as buda_dot_entities_dot_product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/signup.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x62uda/entities/signup.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uda/entities/product.proto\"\xab\x05\n\x06Signup\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12\x1e\n\nvisitor_id\x18\x03 \x01(\x0b\x32\n.buda.Uuid\x12%\n\x11legacy_visitor_id\x18\x64 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x06\x63lient\x18\x05 \x01(\x0e\x32\x19.buda.Signup.SignupClient\x12)\n\x06option\x18\x06 \x01(\x0e\x32\x19.buda.Signup.SignupOption\x12\x1e\n\x16was_created_with_trial\x18\x07 \x01(\x08\x12\x1e\n\x07product\x18\x08 \x01(\x0e\x32\r.buda.Product\x12\x0b\n\x03\x63ta\x18\t \x01(\t\x12*\n\nuser_agent\x18\n \x01(\x0b\x32\x16.buda.Signup.UserAgent\x12\x1d\n\tclient_id\x18\x0b \x01(\x0b\x32\n.buda.Uuid\x12\x1e\n\naccount_id\x18\x0c \x01(\x0b\x32\n.buda.Uuid\x1aI\n\tUserAgent\x12\x0f\n\x07\x62rowser\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\"_\n\x0cSignupOption\x12\t\n\x05\x45MAIL\x10\x00\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x01\x12\x0b\n\x07TWITTER\x10\x02\x12\x0c\n\x08LINKEDIN\x10\x03\x12\n\n\x06GOOGLE\x10\x04\x12\x0f\n\x0bTEAM_INVITE\x10\x05\";\n\x0cSignupClient\x12\x07\n\x03WEB\x10\x00\x12\n\n\x06IPHONE\x10\x04\x12\x0b\n\x07\x41NDROID\x10\x05\x12\t\n\x05OTHER\x10\x06\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,buda_dot_entities_dot_product__pb2.DESCRIPTOR,])



_SIGNUP_SIGNUPOPTION = _descriptor.EnumDescriptor(
  name='SignupOption',
  full_name='buda.Signup.SignupOption',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACEBOOK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWITTER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINKEDIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEAM_INVITE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=652,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_SIGNUP_SIGNUPOPTION)

_SIGNUP_SIGNUPCLIENT = _descriptor.EnumDescriptor(
  name='SignupClient',
  full_name='buda.Signup.SignupClient',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WEB', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPHONE', index=1, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=2, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=3, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=749,
  serialized_end=808,
)
_sym_db.RegisterEnumDescriptor(_SIGNUP_SIGNUPCLIENT)


_SIGNUP_USERAGENT = _descriptor.Descriptor(
  name='UserAgent',
  full_name='buda.Signup.UserAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='browser', full_name='buda.Signup.UserAgent.browser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='buda.Signup.UserAgent.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os', full_name='buda.Signup.UserAgent.os', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='buda.Signup.UserAgent.device', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=650,
)

_SIGNUP = _descriptor.Descriptor(
  name='Signup',
  full_name='buda.Signup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Signup.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.Signup.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitor_id', full_name='buda.Signup.visitor_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='legacy_visitor_id', full_name='buda.Signup.legacy_visitor_id', index=3,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.Signup.created_at', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='buda.Signup.client', index=5,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option', full_name='buda.Signup.option', index=6,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='was_created_with_trial', full_name='buda.Signup.was_created_with_trial', index=7,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='buda.Signup.product', index=8,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cta', full_name='buda.Signup.cta', index=9,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='buda.Signup.user_agent', index=10,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='buda.Signup.client_id', index=11,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='buda.Signup.account_id', index=12,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SIGNUP_USERAGENT, ],
  enum_types=[
    _SIGNUP_SIGNUPOPTION,
    _SIGNUP_SIGNUPCLIENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=808,
)

_SIGNUP_USERAGENT.containing_type = _SIGNUP
_SIGNUP.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['legacy_visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SIGNUP.fields_by_name['client'].enum_type = _SIGNUP_SIGNUPCLIENT
_SIGNUP.fields_by_name['option'].enum_type = _SIGNUP_SIGNUPOPTION
_SIGNUP.fields_by_name['product'].enum_type = buda_dot_entities_dot_product__pb2._PRODUCT
_SIGNUP.fields_by_name['user_agent'].message_type = _SIGNUP_USERAGENT
_SIGNUP.fields_by_name['client_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['account_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP_SIGNUPOPTION.containing_type = _SIGNUP
_SIGNUP_SIGNUPCLIENT.containing_type = _SIGNUP
DESCRIPTOR.message_types_by_name['Signup'] = _SIGNUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signup = _reflection.GeneratedProtocolMessageType('Signup', (_message.Message,), dict(

  UserAgent = _reflection.GeneratedProtocolMessageType('UserAgent', (_message.Message,), dict(
    DESCRIPTOR = _SIGNUP_USERAGENT,
    __module__ = 'buda.entities.signup_pb2'
    # @@protoc_insertion_point(class_scope:buda.Signup.UserAgent)
    ))
  ,
  DESCRIPTOR = _SIGNUP,
  __module__ = 'buda.entities.signup_pb2'
  # @@protoc_insertion_point(class_scope:buda.Signup)
  ))
_sym_db.RegisterMessage(Signup)
_sym_db.RegisterMessage(Signup.UserAgent)


# @@protoc_insertion_point(module_scope)
