# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/signin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buda.entities import product_pb2 as buda_dot_entities_dot_product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/signin.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x62uda/entities/signin.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uda/entities/product.proto\"\xa5\x05\n\x06Signin\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12\x1e\n\nvisitor_id\x18\x03 \x01(\x0b\x32\n.buda.Uuid\x12%\n\x11legacy_visitor_id\x18\x64 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x06\x63lient\x18\x05 \x01(\x0e\x32\x19.buda.Signin.SigninClient\x12)\n\x06option\x18\x06 \x01(\x0e\x32\x19.buda.Signin.SigninOption\x12\x1e\n\x07product\x18\x07 \x01(\x0e\x32\r.buda.Product\x12*\n\nuser_agent\x18\x08 \x01(\x0b\x32\x16.buda.Signin.UserAgent\x12\x1d\n\tclient_id\x18\t \x01(\x0b\x32\n.buda.Uuid\x12\x10\n\x08referrer\x18\n \x01(\t\x12\n\n\x02ip\x18\x0b \x01(\t\x12\x1e\n\naccount_id\x18\x0c \x01(\x0b\x32\n.buda.Uuid\x1aI\n\tUserAgent\x12\x0f\n\x07\x62rowser\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\"N\n\x0cSigninOption\x12\t\n\x05\x45MAIL\x10\x00\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x01\x12\x0b\n\x07TWITTER\x10\x02\x12\x0c\n\x08LINKEDIN\x10\x03\x12\n\n\x06GOOGLE\x10\x04\"U\n\x0cSigninClient\x12\x07\n\x03WEB\x10\x00\x12\x0b\n\x07PUBLISH\x10\x01\x12\x0b\n\x07\x41NALYZE\x10\x03\x12\n\n\x06IPHONE\x10\x04\x12\x0b\n\x07\x41NDROID\x10\x05\x12\t\n\x05OTHER\x10\x06\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,buda_dot_entities_dot_product__pb2.DESCRIPTOR,])



_SIGNIN_SIGNINOPTION = _descriptor.EnumDescriptor(
  name='SigninOption',
  full_name='buda.Signin.SigninOption',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACEBOOK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWITTER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINKEDIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=637,
  serialized_end=715,
)
_sym_db.RegisterEnumDescriptor(_SIGNIN_SIGNINOPTION)

_SIGNIN_SIGNINCLIENT = _descriptor.EnumDescriptor(
  name='SigninClient',
  full_name='buda.Signin.SigninClient',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WEB', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLISH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANALYZE', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPHONE', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=5, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=717,
  serialized_end=802,
)
_sym_db.RegisterEnumDescriptor(_SIGNIN_SIGNINCLIENT)


_SIGNIN_USERAGENT = _descriptor.Descriptor(
  name='UserAgent',
  full_name='buda.Signin.UserAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='browser', full_name='buda.Signin.UserAgent.browser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='buda.Signin.UserAgent.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os', full_name='buda.Signin.UserAgent.os', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='buda.Signin.UserAgent.device', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=635,
)

_SIGNIN = _descriptor.Descriptor(
  name='Signin',
  full_name='buda.Signin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Signin.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.Signin.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitor_id', full_name='buda.Signin.visitor_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='legacy_visitor_id', full_name='buda.Signin.legacy_visitor_id', index=3,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.Signin.created_at', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='buda.Signin.client', index=5,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option', full_name='buda.Signin.option', index=6,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='buda.Signin.product', index=7,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='buda.Signin.user_agent', index=8,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='buda.Signin.client_id', index=9,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referrer', full_name='buda.Signin.referrer', index=10,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='buda.Signin.ip', index=11,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='buda.Signin.account_id', index=12,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SIGNIN_USERAGENT, ],
  enum_types=[
    _SIGNIN_SIGNINOPTION,
    _SIGNIN_SIGNINCLIENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=802,
)

_SIGNIN_USERAGENT.containing_type = _SIGNIN
_SIGNIN.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN.fields_by_name['visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN.fields_by_name['legacy_visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SIGNIN.fields_by_name['client'].enum_type = _SIGNIN_SIGNINCLIENT
_SIGNIN.fields_by_name['option'].enum_type = _SIGNIN_SIGNINOPTION
_SIGNIN.fields_by_name['product'].enum_type = buda_dot_entities_dot_product__pb2._PRODUCT
_SIGNIN.fields_by_name['user_agent'].message_type = _SIGNIN_USERAGENT
_SIGNIN.fields_by_name['client_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN.fields_by_name['account_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNIN_SIGNINOPTION.containing_type = _SIGNIN
_SIGNIN_SIGNINCLIENT.containing_type = _SIGNIN
DESCRIPTOR.message_types_by_name['Signin'] = _SIGNIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signin = _reflection.GeneratedProtocolMessageType('Signin', (_message.Message,), dict(

  UserAgent = _reflection.GeneratedProtocolMessageType('UserAgent', (_message.Message,), dict(
    DESCRIPTOR = _SIGNIN_USERAGENT,
    __module__ = 'buda.entities.signin_pb2'
    # @@protoc_insertion_point(class_scope:buda.Signin.UserAgent)
    ))
  ,
  DESCRIPTOR = _SIGNIN,
  __module__ = 'buda.entities.signin_pb2'
  # @@protoc_insertion_point(class_scope:buda.Signin)
  ))
_sym_db.RegisterMessage(Signin)
_sym_db.RegisterMessage(Signin.UserAgent)


# @@protoc_insertion_point(module_scope)
