# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/subscription_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/subscription_status.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'buda/entities/subscription_status.proto\x12\x04\x62uda*W\n\x12SubscriptionStatus\x12\x0c\n\x08TRIALING\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08PAST_DUE\x10\x02\x12\x0c\n\x08\x43\x41NCELED\x10\x03\x12\x0b\n\x07\x45XPIRED\x10\x04\x62\x06proto3')
)

_SUBSCRIPTIONSTATUS = _descriptor.EnumDescriptor(
  name='SubscriptionStatus',
  full_name='buda.SubscriptionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRIALING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAST_DUE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPIRED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=49,
  serialized_end=136,
)
_sym_db.RegisterEnumDescriptor(_SUBSCRIPTIONSTATUS)

SubscriptionStatus = enum_type_wrapper.EnumTypeWrapper(_SUBSCRIPTIONSTATUS)
TRIALING = 0
ACTIVE = 1
PAST_DUE = 2
CANCELED = 3
EXPIRED = 4


DESCRIPTOR.enum_types_by_name['SubscriptionStatus'] = _SUBSCRIPTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
