# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/subscription_period_updated.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buda.entities import subscription_status_pb2 as buda_dot_entities_dot_subscription__status__pb2
from buda.entities import payment_type_pb2 as buda_dot_entities_dot_payment__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/subscription_period_updated.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/buda/entities/subscription_period_updated.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\'buda/entities/subscription_status.proto\x1a buda/entities/payment_type.proto\"\xa1\x04\n\x19SubscriptionPeriodUpdated\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x42\n\x0csubscription\x18\x04 \x01(\x0b\x32,.buda.SubscriptionPeriodUpdated.Subscription\x12\x38\n\x07payment\x18\x05 \x01(\x0b\x32\'.buda.SubscriptionPeriodUpdated.Payment\x1a\xba\x01\n\x0cSubscription\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12(\n\x06status\x18\x02 \x01(\x0e\x32\x18.buda.SubscriptionStatus\x12\x34\n\x10new_period_start\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0enew_period_end\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x64\n\x07Payment\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.buda.PaymentType\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,buda_dot_entities_dot_subscription__status__pb2.DESCRIPTOR,buda_dot_entities_dot_payment__type__pb2.DESCRIPTOR,])




_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='buda.SubscriptionPeriodUpdated.Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.SubscriptionPeriodUpdated.Subscription.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='buda.SubscriptionPeriodUpdated.Subscription.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_period_start', full_name='buda.SubscriptionPeriodUpdated.Subscription.new_period_start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_period_end', full_name='buda.SubscriptionPeriodUpdated.Subscription.new_period_end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=635,
)

_SUBSCRIPTIONPERIODUPDATED_PAYMENT = _descriptor.Descriptor(
  name='Payment',
  full_name='buda.SubscriptionPeriodUpdated.Payment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.SubscriptionPeriodUpdated.Payment.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='buda.SubscriptionPeriodUpdated.Payment.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='buda.SubscriptionPeriodUpdated.Payment.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='buda.SubscriptionPeriodUpdated.Payment.currency', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=737,
)

_SUBSCRIPTIONPERIODUPDATED = _descriptor.Descriptor(
  name='SubscriptionPeriodUpdated',
  full_name='buda.SubscriptionPeriodUpdated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.SubscriptionPeriodUpdated.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.SubscriptionPeriodUpdated.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.SubscriptionPeriodUpdated.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscription', full_name='buda.SubscriptionPeriodUpdated.subscription', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment', full_name='buda.SubscriptionPeriodUpdated.payment', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION, _SUBSCRIPTIONPERIODUPDATED_PAYMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=737,
)

_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION.fields_by_name['status'].enum_type = buda_dot_entities_dot_subscription__status__pb2._SUBSCRIPTIONSTATUS
_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION.fields_by_name['new_period_start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION.fields_by_name['new_period_end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION.containing_type = _SUBSCRIPTIONPERIODUPDATED
_SUBSCRIPTIONPERIODUPDATED_PAYMENT.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SUBSCRIPTIONPERIODUPDATED_PAYMENT.fields_by_name['type'].enum_type = buda_dot_entities_dot_payment__type__pb2._PAYMENTTYPE
_SUBSCRIPTIONPERIODUPDATED_PAYMENT.containing_type = _SUBSCRIPTIONPERIODUPDATED
_SUBSCRIPTIONPERIODUPDATED.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SUBSCRIPTIONPERIODUPDATED.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SUBSCRIPTIONPERIODUPDATED.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SUBSCRIPTIONPERIODUPDATED.fields_by_name['subscription'].message_type = _SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION
_SUBSCRIPTIONPERIODUPDATED.fields_by_name['payment'].message_type = _SUBSCRIPTIONPERIODUPDATED_PAYMENT
DESCRIPTOR.message_types_by_name['SubscriptionPeriodUpdated'] = _SUBSCRIPTIONPERIODUPDATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriptionPeriodUpdated = _reflection.GeneratedProtocolMessageType('SubscriptionPeriodUpdated', (_message.Message,), dict(

  Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), dict(
    DESCRIPTOR = _SUBSCRIPTIONPERIODUPDATED_SUBSCRIPTION,
    __module__ = 'buda.entities.subscription_period_updated_pb2'
    # @@protoc_insertion_point(class_scope:buda.SubscriptionPeriodUpdated.Subscription)
    ))
  ,

  Payment = _reflection.GeneratedProtocolMessageType('Payment', (_message.Message,), dict(
    DESCRIPTOR = _SUBSCRIPTIONPERIODUPDATED_PAYMENT,
    __module__ = 'buda.entities.subscription_period_updated_pb2'
    # @@protoc_insertion_point(class_scope:buda.SubscriptionPeriodUpdated.Payment)
    ))
  ,
  DESCRIPTOR = _SUBSCRIPTIONPERIODUPDATED,
  __module__ = 'buda.entities.subscription_period_updated_pb2'
  # @@protoc_insertion_point(class_scope:buda.SubscriptionPeriodUpdated)
  ))
_sym_db.RegisterMessage(SubscriptionPeriodUpdated)
_sym_db.RegisterMessage(SubscriptionPeriodUpdated.Subscription)
_sym_db.RegisterMessage(SubscriptionPeriodUpdated.Payment)


# @@protoc_insertion_point(module_scope)
