# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/uuid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/uuid.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x62uda/entities/uuid.proto\x12\x04\x62uda\"\x12\n\x04Uuid\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')
)




_UUID = _descriptor.Descriptor(
  name='Uuid',
  full_name='buda.Uuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Uuid.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Uuid'] = _UUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Uuid = _reflection.GeneratedProtocolMessageType('Uuid', (_message.Message,), dict(
  DESCRIPTOR = _UUID,
  __module__ = 'buda.entities.uuid_pb2'
  # @@protoc_insertion_point(class_scope:buda.Uuid)
  ))
_sym_db.RegisterMessage(Uuid)


# @@protoc_insertion_point(module_scope)
