# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/visit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buda.entities import product_pb2 as buda_dot_entities_dot_product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/visit.proto',
  package='buda',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x62uda/entities/visit.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uda/entities/product.proto\"\xba\x04\n\x05Visit\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1e\n\nvisitor_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x03 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03uri\x18\x05 \x01(\t\x12\n\n\x02ip\x18\x06 \x01(\t\x12\x1c\n\x03utm\x18\x07 \x01(\x0b\x32\x0f.buda.Visit.Utm\x12)\n\nuser_agent\x18\x08 \x01(\x0b\x32\x15.buda.Visit.UserAgent\x12\x10\n\x08referrer\x18\t \x01(\t\x12\x0e\n\x06\x64omain\x18\n \x01(\t\x12+\n\x0b\x65xperiments\x18\x0b \x03(\x0b\x32\x16.buda.Visit.Experiment\x12\x0e\n\x06source\x18\x0c \x01(\t\x12\x1e\n\x07product\x18\r \x01(\x0e\x32\r.buda.Product\x12\x0b\n\x03\x63ta\x18\x0e \x01(\t\x1a-\n\tUserAgent\x12\x0f\n\x07\x62rowser\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x1aV\n\x03Utm\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06medium\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61mpaign\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0c\n\x04term\x18\x05 \x01(\t\x1a\x37\n\nExperiment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,buda_dot_entities_dot_product__pb2.DESCRIPTOR,])




_VISIT_USERAGENT = _descriptor.Descriptor(
  name='UserAgent',
  full_name='buda.Visit.UserAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='browser', full_name='buda.Visit.UserAgent.browser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='buda.Visit.UserAgent.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=549,
)

_VISIT_UTM = _descriptor.Descriptor(
  name='Utm',
  full_name='buda.Visit.Utm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='buda.Visit.Utm.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='medium', full_name='buda.Visit.Utm.medium', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='campaign', full_name='buda.Visit.Utm.campaign', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='buda.Visit.Utm.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='buda.Visit.Utm.term', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=637,
)

_VISIT_EXPERIMENT = _descriptor.Descriptor(
  name='Experiment',
  full_name='buda.Visit.Experiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Visit.Experiment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='buda.Visit.Experiment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='buda.Visit.Experiment.enabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=694,
)

_VISIT = _descriptor.Descriptor(
  name='Visit',
  full_name='buda.Visit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Visit.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitor_id', full_name='buda.Visit.visitor_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.Visit.user_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.Visit.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='buda.Visit.uri', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='buda.Visit.ip', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utm', full_name='buda.Visit.utm', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='buda.Visit.user_agent', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referrer', full_name='buda.Visit.referrer', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='buda.Visit.domain', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiments', full_name='buda.Visit.experiments', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='buda.Visit.source', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='buda.Visit.product', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cta', full_name='buda.Visit.cta', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VISIT_USERAGENT, _VISIT_UTM, _VISIT_EXPERIMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=694,
)

_VISIT_USERAGENT.containing_type = _VISIT
_VISIT_UTM.containing_type = _VISIT
_VISIT_EXPERIMENT.containing_type = _VISIT
_VISIT.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_VISIT.fields_by_name['visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_VISIT.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_VISIT.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_VISIT.fields_by_name['utm'].message_type = _VISIT_UTM
_VISIT.fields_by_name['user_agent'].message_type = _VISIT_USERAGENT
_VISIT.fields_by_name['experiments'].message_type = _VISIT_EXPERIMENT
_VISIT.fields_by_name['product'].enum_type = buda_dot_entities_dot_product__pb2._PRODUCT
DESCRIPTOR.message_types_by_name['Visit'] = _VISIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Visit = _reflection.GeneratedProtocolMessageType('Visit', (_message.Message,), dict(

  UserAgent = _reflection.GeneratedProtocolMessageType('UserAgent', (_message.Message,), dict(
    DESCRIPTOR = _VISIT_USERAGENT,
    __module__ = 'buda.entities.visit_pb2'
    # @@protoc_insertion_point(class_scope:buda.Visit.UserAgent)
    ))
  ,

  Utm = _reflection.GeneratedProtocolMessageType('Utm', (_message.Message,), dict(
    DESCRIPTOR = _VISIT_UTM,
    __module__ = 'buda.entities.visit_pb2'
    # @@protoc_insertion_point(class_scope:buda.Visit.Utm)
    ))
  ,

  Experiment = _reflection.GeneratedProtocolMessageType('Experiment', (_message.Message,), dict(
    DESCRIPTOR = _VISIT_EXPERIMENT,
    __module__ = 'buda.entities.visit_pb2'
    # @@protoc_insertion_point(class_scope:buda.Visit.Experiment)
    ))
  ,
  DESCRIPTOR = _VISIT,
  __module__ = 'buda.entities.visit_pb2'
  # @@protoc_insertion_point(class_scope:buda.Visit)
  ))
_sym_db.RegisterMessage(Visit)
_sym_db.RegisterMessage(Visit.UserAgent)
_sym_db.RegisterMessage(Visit.Utm)
_sym_db.RegisterMessage(Visit.Experiment)


# @@protoc_insertion_point(module_scope)
