apiVersion: v1
kind: Service
metadata:
    name: events-collector
    namespace: data
    labels:
        app: events-collector
spec:
    ports:
        - name: grpc
          port: 50051
    selector:
        app: events-collector
