# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/funnel_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from buda.entities import link_pb2 as buda_dot_entities_dot_link__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/funnel_event.proto',
  package='buda.entities',
  syntax='proto3',
  serialized_pb=_b('\n buda/entities/funnel_event.proto\x12\rbuda.entities\x1a\x18\x62uda/entities/uuid.proto\x1a\x18\x62uda/entities/link.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x02\n\x0b\x46unnelEvent\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.buda.entities.UUID\x12&\n\tfunnel_id\x18\x02 \x01(\x0b\x32\x13.buda.entities.UUID\x12+\n\x0e\x66unnel_step_id\x18\x03 \x01(\x0b\x32\x13.buda.entities.UUID\x12$\n\x07user_id\x18\x04 \x01(\x0b\x32\x13.buda.entities.UUID\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x04tags\x18\x06 \x03(\x0b\x32$.buda.entities.FunnelEvent.TagsEntry\x12\x12\n\nfunnel_end\x18\x10 \x01(\x08\x12\"\n\x05links\x18\x11 \x03(\x0b\x32\x13.buda.entities.Link\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,buda_dot_entities_dot_link__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FUNNELEVENT_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='buda.entities.FunnelEvent.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='buda.entities.FunnelEvent.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='buda.entities.FunnelEvent.TagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=507,
)

_FUNNELEVENT = _descriptor.Descriptor(
  name='FunnelEvent',
  full_name='buda.entities.FunnelEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.entities.FunnelEvent.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funnel_id', full_name='buda.entities.FunnelEvent.funnel_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funnel_step_id', full_name='buda.entities.FunnelEvent.funnel_step_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.entities.FunnelEvent.user_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.entities.FunnelEvent.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='buda.entities.FunnelEvent.tags', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='funnel_end', full_name='buda.entities.FunnelEvent.funnel_end', index=6,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='buda.entities.FunnelEvent.links', index=7,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FUNNELEVENT_TAGSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=507,
)

_FUNNELEVENT_TAGSENTRY.containing_type = _FUNNELEVENT
_FUNNELEVENT.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNELEVENT.fields_by_name['funnel_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNELEVENT.fields_by_name['funnel_step_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNELEVENT.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_FUNNELEVENT.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FUNNELEVENT.fields_by_name['tags'].message_type = _FUNNELEVENT_TAGSENTRY
_FUNNELEVENT.fields_by_name['links'].message_type = buda_dot_entities_dot_link__pb2._LINK
DESCRIPTOR.message_types_by_name['FunnelEvent'] = _FUNNELEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FunnelEvent = _reflection.GeneratedProtocolMessageType('FunnelEvent', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _FUNNELEVENT_TAGSENTRY,
    __module__ = 'buda.entities.funnel_event_pb2'
    # @@protoc_insertion_point(class_scope:buda.entities.FunnelEvent.TagsEntry)
    ))
  ,
  DESCRIPTOR = _FUNNELEVENT,
  __module__ = 'buda.entities.funnel_event_pb2'
  # @@protoc_insertion_point(class_scope:buda.entities.FunnelEvent)
  ))
_sym_db.RegisterMessage(FunnelEvent)
_sym_db.RegisterMessage(FunnelEvent.TagsEntry)


_FUNNELEVENT_TAGSENTRY.has_options = True
_FUNNELEVENT_TAGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
