# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/uuid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/uuid.proto',
  package='buda.entities',
  syntax='proto3',
  serialized_pb=_b('\n\x18\x62uda/entities/uuid.proto\x12\rbuda.entities\"\x12\n\x04UUID\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')
)




_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='buda.entities.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.entities.UUID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['UUID'] = _UUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), dict(
  DESCRIPTOR = _UUID,
  __module__ = 'buda.entities.uuid_pb2'
  # @@protoc_insertion_point(class_scope:buda.entities.UUID)
  ))
_sym_db.RegisterMessage(UUID)


# @@protoc_insertion_point(module_scope)
